### ISSUE TITLE
睡宝，帮我做做选择！

### ISSUE THREAD

**Issue by Sunnky99** [fceek/SleepyBot#1]
想要这样的功能！
—当我提出“对吗？”
—会随机回复“对！/不对！”

或者答案之书！https://github.com/D1N910/answers-of-my-life
—当我在句子中加入“答案之书”
—会随机回复答案之书中的某个答案。

**Comment by fceek** [comment]
答案之书已实装于 20f50e6f97eca361f86734e61df6247cb4ac12b3

**Comment by Sunnky99** [comment]
Thank
you!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Lost sheep can find its way to fall asleep now.
